/* Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Link: https://projecteuler.net/problem=2
 */

public class Problem2 {

    public static void main(String []args) {
        System.out.println(sumOfevenvalues_in_Fibo(4000000)); // Enter the length of Fibonacci Sequence
    }

    public static int sumOfevenvalues_in_Fibo(int maximum){
        int sum = 0;
        int x = 1;
        int y = 2;
        while (x < maximum){
            if( x % 2 == 0 ){
                sum += x;
            }
            int temp = x + y;
            x = y;
            y = temp;
        }
        return sum;
    }
}